version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/app"
      - "/nginx"
    schedule: { interval: "daily" }
    target-branch: "main"

  - package-ecosystem: "docker-compose"
    directory: "."
    schedule: { interval: "daily" }
    target-branch: "main"

  - package-ecosystem: "pip"
    directory: "/app"
    schedule: { interval: "daily" }
    target-branch: "main"
