version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/app"
      - "/nginx"
    schedule: { interval: "weekly" }
    target-branch: "main"
    open-pull-requests-limit: 0

  - package-ecosystem: "docker-compose"
    directory: "."
    schedule: { interval: "weekly" }
    target-branch: "main"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/app"
    schedule: { interval: "monthly" }
    target-branch: "main"
    groups:
      production:
        dependency-type: 'production'
        patterns:
          - '*'
      development:
        dependency-type: 'development'
        patterns:
          - '*'
