services:

  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

  web:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: app_web
    ports:
      - '8000:8000'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: web
  
  db:
    image: postgis/postgis:14-master
    platform: linux/amd64
    shm_size: 1gb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 5
  
  worker:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: app_worker
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A app worker --loglevel=INFO --concurrency=6
    volumes:
      - ./app:/app
      - ./source_data:/data/downloads
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    container_name: worker

  celery_beat:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: app_worker
    command: celery -A app beat --loglevel=INFO
    volumes:
      - ./app:/app
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: celery_beat
  
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3.9-alpine
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 15s
      retries: 5
      start_period: 20s
      timeout: 5s
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
  
  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --url_prefix=flower
    ports:
      - 5555:5555
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data:
