name: rnb-coeur

services:
  web:
    extends:
      file: common-services.yml
      service: web
    environment:
      - DEBUG=1
      - DJANGO_ENV=test
      - DJANGO_SECRET_KEY=FOR_TEST_ONLY_eTPoJ4J132rg3UhQUAYAYOGljoh6MX8V
      - DJANGO_ALLOWED_HOST=localhost 127.0.0.1 [::1]
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://127.0.0.1
      - DJANGO_CORS_ALLOWED_ORIGINS=http://127.0.0.1:5500
      - DJANGO_SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - DJANGO_SUPERUSER_PASSWORD=1234
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOWNLOAD_DIR=/data/downloads
      - MIN_BDG_AREA=5
      - WAIT_HOSTS=db:5432 rabbitmq:5672 redis:6379
      - WAIT_BEFORE=8
      - MATTERMOST_NOTIFICATIONS=0
      - URL=http://dummy.fake
      - FRONTEND_URL=http://front.fake
      - DJANGO_EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
      - DJANGO_EMAIL_HOST=dummy_email_host
      - DJANGO_EMAIL_PORT=dummy_email_port
      - DJANGO_EMAIL_HOST_USER=dummy_email_host_user
      - DJANGO_EMAIL_HOST_PASSWORD=dummy_email_host_password
      - DJANGO_EMAIL_USE_TLS=0
      - DJANGO_EMAIL_USE_SSL=1
    build:
      args:
        - WITH_DEV_DEPENDENCIES=true
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    extends:
      file: common-services.yml
      service: db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file: []

  redis:
    extends:
      file: common-services.yml
      service: redis

volumes:
  postgres_data:
  rabbitmq_data:
