name: rnb-coeur

services:
  # Uncomment this to use Nginx locally
  # nginx-proxy:
  #   extends:
  #     file: common-services.yml
  #     service: nginx-proxy

  web:
    extends:
      file: common-services.yml
      service: web
    ports:
      - '8888:8888' # Jupyter notebook
      - '5678:5678'
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source_data:/data/downloads
    env_file:
      - ./.env.db_auth.dev
      - ./.env.app.dev
      - ./.env.worker.dev
      - ./.env.rnb.dev
    build:
      args:
        - WITH_DEV_DEPENDENCIES=true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - URL=http://localhost:8000

    networks:
      - rnb_dev_network
      # This is to test Nginx proxy locally, but it's not required if you are targeting
      # the Django application directly.
      # If you want to test something on Nginx, you will have to add the following to
      # your /etc/hosts file:
      #   127.0.0.1 rnb-api.dev
      # And uncomment the following lines
      # - VIRTUAL_HOST=rnb-api.dev
      # - DJANGO_ALLOWED_HOST=rnb-api.dev
      # - VIRTUAL_PORT=8000
      # - VIRTUAL_PROTO=http
  db:
    extends:
      file: common-services.yml
      service: db
    env_file:
      - ./.env.db_auth.dev
    ports:
      - "5432:5432"

  worker:
    extends:
      file: common-services.yml
      service: worker
    env_file:
      - ./.env.db_auth.dev
      - ./.env.app.dev
      - ./.env.worker.dev
      - ./.env.rnb.dev
      - ./.env.s3_backup.dev
    build:
      args:
        - WITH_DEV_DEPENDENCIES=true
    depends_on:
      db:
        condition: service_healthy

  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  redis:
    extends:
      file: common-services.yml
      service: redis

  flower:
    extends:
      file: common-services.yml
      service: flower
    env_file:
      - ./.env.worker.dev

  metabase:
    extends:
      file: common-services.yml
      service: metabase
    env_file:
      - ./.env.metabase.dev

volumes:
  postgres_data:
  rabbitmq_data:
   certs:
  html:
networks:
  rnb_dev_network:
    external: true


