name: rnb-coeur

services:
  web:
    extends:
      file: common-services.yml
      service: web
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=FOR_TEST_ONLY_eTPoJ4J132rg3UhQUAYAYOGljoh6MX8V
      - DJANGO_ALLOWED_HOST=localhost 127.0.0.1 [::1]
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://127.0.0.1
      - DJANGO_CORS_ALLOWED_ORIGINS=http://127.0.0.1:5500
      - DJANGO_SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - DJANGO_SUPERUSER_PASSWORD=1234
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=34e6daf423a79ada371a01c5f367bb27
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOWNLOAD_DIR=/data/downloads
      - MIN_BDG_AREA=5
      - WAIT_HOSTS=db:5432 rabbitmq:5672 redis:6379
      - WAIT_BEFORE=8
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  db:
    extends:
      file: common-services.yml
      service: db
    # ports:
    #   - "5434:5432"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=34e6daf423a79ada371a01c5f367bb27
    restart: always

  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    extends:
      file: common-services.yml
      service: redis

volumes:
  postgres_data:
  rabbitmq_data: