name: rnb-coeur

services:
  web:
    extends:
      file: common-services.yml
      service: web
    ports:
      - '8888:8888' # Jupyter notebook
    volumes:
      - ./source_data:/data/downloads
    env_file:
      - ./.env.db_auth.dev
      - ./.env.app.dev
      - ./.env.worker.dev
      - ./.env.rnb.dev
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    extends:
      file: common-services.yml
      service: db
    env_file:
      - ./.env.db_auth.dev
    ports:
      - "5442:5432"

  worker:
    extends:
      file: common-services.yml
      service: worker
    env_file:
      - ./.env.db_auth.dev
      - ./.env.app.dev
      - ./.env.worker.dev
      - ./.env.rnb.dev
      - ./.env.s3_backup.dev
    depends_on:
      db:
        condition: service_healthy

  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  redis:
    extends:
      file: common-services.yml
      service: redis

  flower:
    extends:
      file: common-services.yml
      service: flower
    env_file:
      - ./.env.worker.dev

volumes:
  postgres_data:
  rabbitmq_data:
