from typing import Any
from rest_framework import serializers

class TagListSerializerField(serializers.Field):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def to_internal_value(self, data: Any) -> Any: ...
    def to_representation(self, value: Any) -> Any: ...

class TaggitSerializer(serializers.ModelSerializer):
    def create(self, validated_data: Any) -> Any: ...
    def update(self, instance: Any, validated_data: Any) -> Any: ...
