"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

import sentry_sdk
from kombu import Exchange
from kombu import Queue
from sentry_sdk.integrations.django import DjangoIntegration

from app.schedule import get_celery_beat_schedule

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WRITABLE_DATA_DIR = os.path.join(BASE_DIR, "data")

PRIVATE_CAPTCHA_API_KEY = os.environ.get("PRIVATE_CAPTCHA_API_KEY")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("DEBUG", default=0))

ENVIRONMENT = os.environ["DJANGO_ENV"]  # This is mandatory
HAS_SANDBOX = str(os.environ.get("HAS_SANDBOX", default="false")) == "true"
SANDBOX_URL = os.environ.get("SANDBOX_URL", default=None)
SANDBOX_SECRET_TOKEN = os.environ.get("SANDBOX_SECRET_TOKEN", default=None)

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOST").split(" ")  # type: ignore[union-attr]
CSRF_TRUSTED_ORIGINS = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS").split(" ")  # type: ignore[union-attr]

CORS_ALLOWED_ORIGINS = os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS").split(" ")  # type: ignore[union-attr]
CORS_ALLOW_ALL_ORIGINS = True

LOGIN_URL = "/admin/login/"

DATABASE_ROUTERS = ("app.dbrouters.DBRouter",)

if DEBUG:
    import socket  # only if you haven't already imported this

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + [
        "127.0.0.1",
        "10.0.2.2",
    ]

    NOTEBOOK_ARGUMENTS = [
        "--ip",
        "0.0.0.0",  # nosec B104
        "--allow-root",
        "--no-browser",
    ]  # see https://stackoverflow.com/a/47063057/1892308

# Application definition

INSTALLED_APPS = [
    "debug_toolbar",
    "jsoneditor",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_gis",
    "django.contrib.postgres",
    "corsheaders",
    "rest_framework_tracking",
    "batid",
    "website",
    "api_alpha",
    "webhook",
    "xp",
    "django_extensions",
    "revproxy",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "batid.middlewares.BlockIPMiddleware",
    "batid.middlewares.SimpleRequestLoggerMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

STATIC_ROOT = os.path.join(BASE_DIR, "static")


SERIALIZATION_MODULES = {
    "geojson": "django.contrib.gis.serializers.geojson",
}

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {  # type: ignore[var-annotated]
    "default": {
        "ENGINE": os.environ.get("DJANGO_SQL_ENGINE"),
        "NAME": os.environ.get("POSTGRES_NAME"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
        "OPTIONS": {},
    }
}

POSTGRES_STATEMENT_TIMEOUT = os.environ.get("POSTGRES_STATEMENT_TIMEOUT")
DIFF_VIEW_POSTGRES_STATEMENT_TIMEOUT = os.environ.get(
    "DIFF_VIEW_POSTGRES_STATEMENT_TIMEOUT", "0"
)
DATA_GOUV_POSTGRES_STATEMENT_TIMEOUT = os.environ.get(
    "DATA_GOUV_POSTGRES_STATEMENT_TIMEOUT", "259200000"  # Default to 72h
)
if POSTGRES_STATEMENT_TIMEOUT:
    DATABASES["default"]["OPTIONS"][  # type: ignore[index]
        "options"
    ] = f"-c statement_timeout={POSTGRES_STATEMENT_TIMEOUT}"


# any active user part of this group can edit the RNB
CONTRIBUTORS_GROUP_NAME = "Contributors"

AUTHENTICATION_BACKENDS = [
    "app.authentication.UsernameOrEmailBackend",
]

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication"
    ],
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 30,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "change_password": "10/day",
        "create_user": "10/day",
    },
    "URL_FORMAT_OVERRIDE": None,
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Documentation de l'API du Référentiel National du Bâtiment (RNB)",
    "VERSION": "0.0.1",
    "SECURITY": [],
    "PREPROCESSING_HOOKS": [
        "api_alpha.utils.drf_spectacular_extension.filter_endpoints_hook"
    ],
}

FRONTEND_URL = os.environ.get("FRONTEND_URL")

EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND")
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST")
EMAIL_PORT = os.environ.get("DJANGO_EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS") == "1"
EMAIL_USE_SSL = os.environ.get("DJANGO_EMAIL_USE_SSL") == "1"

RNB_SEND_ADDRESS = os.environ.get("RNB_SEND_ADDRESS")
RNB_SEND_NAME = "Référentiel National des Bâtiments"
RNB_REPLY_TO_ADDRESS = os.environ.get("RNB_REPLY_TO_ADDRESS")

# Biggest building in RNB is GB97B3AYBKRN and is roughly 487,000m²
MAX_BUILDING_AREA = 500000
MIN_BUILDING_AREA = 5

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_BACKEND_URL = os.environ.get("CELERY_RESULT_BACKEND")
CELERY_TASK_QUEUES = (
    Queue(
        "default",
        Exchange("default"),
        routing_key="default",
        queue_arguments={"x-max-priority": 10},
    ),
)
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_DEFAULT_EXCHANGE = "default"
CELERY_TASK_DEFAULT_ROUTING_KEY = "default"
CELERY_TASK_DEFAULT_PRIORITY = 5
CELERY_WORKER_PREFETCH_MULTIPLIER = 1


CELERY_BEAT_SCHEDULE = get_celery_beat_schedule(ENVIRONMENT)

BLOCKED_IPS = os.environ.get("BLOCKED_IPS", "").split(",")

# URL of the project
URL = os.environ.get("URL")


# Mattermost
MATTERMOST_NOTIFICATIONS = (
    True
    if os.environ.get("MATTERMOST_NOTIFICATIONS") in ("true", "1", "True")
    else False
)

sentry_dsn = os.environ.get("SENTRY_DSN", None)
if sentry_dsn:
    sentry_sdk.init(
        dsn=sentry_dsn,
        integrations=[
            DjangoIntegration(),
        ],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sample_rate=1.0,
        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        send_default_pii=True,
        environment=os.environ.get("SENTRY_ENV"),
    )

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "gunicorn_style": {
            "format": "[%(asctime)s] [%(process)d] [%(levelname)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S %z",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "gunicorn_style",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "rest_framework": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
