server:
  bind:
    host: 0.0.0.0
    port: 8000
  url: http://localhost:8000/api/alpha/ogc
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - fr-FR
  # cors: true
  pretty_print: true
  limits:
    default_items: 10
    max_items: 50
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
logging:
  level: ERROR
metadata:
  identification:
    title: pygeoapi Demo instance - running latest GitHub version
    description: pygeoapi provides an API to geospatial data
    keywords:
      - geospatial
      - data
      - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/geopython/pygeoapi
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: pygeoapi Development Team
    url: https://pygeoapi.io
  contact:
    name: Kralidis, Tom
    position: Lead Dev
    address: Mailing Address
    city: City
    stateorprovince: Administrative Area
    postalcode: Zip or Postal Code
    country: Canada
    phone: +xx-xxx-xxx-xxxx
    fax: +xx-xxx-xxx-xxxx
    email: you@example.org
    url: Contact URL
    hours: Hours of Service
    instructions: During hours of service.  Off on weekends.
    role: pointOfContact

resources:
  buildings:
    type: collection
    title: Buildings
    description: Building footprints
    providers:
      - type: provider
        name: batid.services.geoapi.BuildingProvider
        priority: 1
