[tool.poetry]
name = "app"
version = "0.1.0"
description = "RNB's backend code"
authors = ["RNB team <tech@rnb.beta.gouv.fr>"]

[tool.poetry.dependencies]
python = "3.12.4"
boto3 = "~1.34.126"
Django = "~5.0.7"
drf-spectacular = "~0.27.1"
drf-api-tracking = "~1.8.4"
flower = "~2.0.1"
sentry-sdk = "~1.45.0"
django-debug-toolbar = "~4.4"
djangorestframework-gis = "~1.0"
psycopg2 = "~2.9.9"
django-cors-headers = "~4.4.0"
django-extensions = "~3.2.3"
django-revproxy = "~0.12.0"
nanoid = "~2.0.0"
geopy = "^2.4.1"
whitenoise = "~6.7.0"
watchdog = {extras = ["watchmedo"], version = "^4.0.1"}
celery = "~5.4.0"
py7zr = "~0.21.1"
ijson = "~3.3.0"
redis = "~4.5.4"
gunicorn = "~22.0.0"
requests = "~2.32.2"
pandas = "~2.2.2"
Fiona = "~1.9.6"
djangorestframework = "~3.15.2"
orjson = "^3.10.7"

[tool.poetry.group.dev.dependencies]
moto = "^5.0.9"
freezegun = "^1.5.1"
geopandas = "~1.0.1"
notebook = "~6.5.6"
jupyter = "^1.0.0"
openpyxl = "^3.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
