[tool.poetry]
name = "app"
version = "0.1.0"
description = "RNB's backend code"
authors = ["RNB team <tech@rnb.beta.gouv.fr>"]
package-mode = false

[tool.poetry.dependencies]
python = "3.12.4"
boto3 = "~1.36.0"
Django = "~5.1.7"
drf-spectacular = "~0.28.0"
drf-api-tracking = "~1.8.4"
flower = "~2.0.1"
sentry-sdk = "~2.8.0"
django-debug-toolbar = "~5.0.1"
djangorestframework-gis = "~1.1"
psycopg2 = "~2.9.9"
django-cors-headers = "~4.7.0"
django-extensions = "~3.2.3"
django-revproxy = "~0.13.0"
nanoid = "~2.0.0"
geopy = "^2.4.1"
whitenoise = "~6.9.0"
watchdog = {extras = ["watchmedo"], version = "^4.0.1"}
celery = "~5.4.0"
py7zr = "~0.22.0"
ijson = "~3.3.0"
redis = "~4.5.4"
gunicorn = "~23.0.0"
requests = "~2.32.2"
pandas = "~2.2.2"
Fiona = "~1.10.1"
djangorestframework = "~3.15.2"
geopandas = "^1.0.1"
openapi-spec-validator = "^0.7.1"
orjson = "^3.10.7"
django-jsoneditor = "^0.2.4"

[tool.poetry.group.dev.dependencies]
moto = "^5.0.9"
freezegun = "^1.5.1"
notebook = "~6.5.6"
jupyter = "^1.0.0"
openpyxl = "^3.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
