[tool.poetry]
name = "app"
version = "0.1.0"
description = "RNB's backend code"
authors = ["RNB team <tech@rnb.beta.gouv.fr>"]

[tool.poetry.dependencies]
python = "3.10.14"
boto3 = "1.34.126"
geopandas = "0.12.2"
Django = "4.1.13"
drf-spectacular = "0.27.1"
drf-api-tracking = "1.8.4"
flower = "2.0.1"
sentry-sdk = "1.19.1"
django-debug-toolbar = "~3.8.1"
djangorestframework-gis = "~1.0"
psycopg2 = "2.9.9"
django-cors-headers = "~3.14.0"
django-extensions = "~3.2.3"
django-revproxy = "~0.11.0"
nanoid = "~2.0.0"
geopy = "^2.4.1"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
moto = "^5.0.9"
freezegun = "^1.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
