# Generated by Django 4.1.7 on 2023-02-20 10:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rnb_id', models.CharField(db_index=True, max_length=6, unique=True)),
                ('source', models.CharField(max_length=10)),
                ('point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='batid.building')),
            ],
        ),
        migrations.CreateModel(
            name='ExtRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=10)),
                ('ext_id', models.CharField(db_index=True, max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batid.building')),
            ],
        ),
    ]
