# Generated by Django 4.1.7 on 2023-02-21 11:42
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="ext_ban_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=16),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="ext_bdnb_id",
            field=models.CharField(
                db_index=True, max_length=16, null=True, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="ExtRef",
        ),
    ]
