# Generated by Django 4.1.7 on 2023-02-23 15:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0002_building_ext_ban_ids_building_ext_bdnb_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="ext_bdnb_id",
            field=models.CharField(
                db_index=True, max_length=40, null=True, unique=True
            ),
        ),
    ]
