# Generated by Django 4.1.7 on 2023-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0003_alter_building_ext_bdnb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='rnb_id',
            field=models.CharField(db_index=True, max_length=17, unique=True),
        ),
    ]
