# Generated by Django 4.1.7 on 2023-02-23 16:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0004_alter_building_rnb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='ext_ban_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None),
        ),
    ]
