# Generated by Django 4.1.7 on 2023-02-27 13:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0005_alter_building_ext_ban_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=10)),
                ("street_number", models.CharField(max_length=10, null=True)),
                ("street_name", models.CharField(max_length=100, null=True)),
                ("city_name", models.CharField(max_length=100, null=True)),
                ("city_zipcode", models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="building",
            name="ext_ban_ids",
        ),
        migrations.AddField(
            model_name="building",
            name="addresses",
            field=models.ManyToManyField(
                blank=True, related_name="buildings", to="batid.address"
            ),
        ),
    ]
