# Generated by Django 4.1.7 on 2023-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0006_address_remove_building_ext_ban_ids_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='type',
            new_name='source',
        ),
        migrations.AddField(
            model_name='address',
            name='street_rep',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
