# Generated by Django 4.1.7 on 2023-03-09 13:19
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0007_rename_type_address_source_address_street_rep_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("source", models.CharField(max_length=20)),
                ("source_id", models.CharField(max_length=40)),
                (
                    "ban_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=40), null=True, size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inspected_at", models.DateTimeField(null=True)),
                ("inspect_result", models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="building",
            options={"ordering": ["rnb_id"]},
        ),
        migrations.AddField(
            model_name="building",
            name="ext_bdtopo_id",
            field=models.CharField(
                db_index=True, max_length=40, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="shape",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=4326
            ),
        ),
    ]
