# Generated by Django 4.1.7 on 2023-03-09 16:59
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0008_candidate_alter_building_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="shape",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=4326
            ),
        ),
    ]
