# Generated by Django 4.1.7 on 2023-03-09 17:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0009_alter_candidate_shape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
