# Generated by Django 4.1.7 on 2023-03-10 10:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0012_alter_candidate_created_at_alter_candidate_shape"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="ban_ids",
            new_name="address_keys",
        ),
    ]
