# Generated by Django 4.1.7 on 2023-03-10 13:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0013_rename_ban_ids_candidate_address_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=2154),
        ),
        migrations.AlterField(
            model_name='building',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=2154),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=2154),
        ),
    ]
