# Generated by Django 4.1.7 on 2023-04-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0015_alter_candidate_inspect_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('code_insee', models.CharField(max_length=10)),
                ('uri_insee', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('name_without_article', models.CharField(max_length=200)),
            ],
        ),
    ]
