# Generated by Django 4.1.7 on 2023-04-12 11:25
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batid", "0016_ads_buildingads"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ads",
            options={"ordering": ["issue_date"]},
        ),
        migrations.AlterField(
            model_name="buildingads",
            name="ads",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings_operations",
                to="batid.ads",
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "managed_cities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=6), null=True, size=None
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="organizations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
