# Generated by Django 4.1.7 on 2023-04-12 14:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0017_alter_ads_options_alter_buildingads_ads_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="insee_code",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
