# Generated by Django 4.1.7 on 2023-04-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0016_city'),
        ('batid', '0018_ads_insee_code'),
    ]

    operations = [
    ]
