# Generated by Django 4.1.7 on 2023-04-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0019_merge_0016_city_0018_ads_insee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='source',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
