# Generated by Django 4.1.7 on 2023-04-27 14:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0021_alter_candidate_inspect_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="is_light",
            field=models.BooleanField(null=True),
        ),
    ]
