# Generated by Django 4.1.7 on 2023-04-28 09:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0022_candidate_is_light"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="creation_date",
            new_name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
