# Generated by Django 4.1.7 on 2023-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0023_rename_creation_date_city_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code_insee',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
