# Generated by Django 4.1.7 on 2023-05-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0024_alter_city_code_insee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['decision_date']},
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='issue_date',
            new_name='decision_date',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='issue_number',
            new_name='file_number',
        ),
    ]
