# Generated by Django 4.1.7 on 2023-05-23 12:07
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0025_alter_ads_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="shape",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=2154
            ),
        ),
    ]
