# Generated by Django 4.1.7 on 2023-05-23 12:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0026_city_shape"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="created_at",
            new_name="established_at",
        ),
        migrations.RemoveField(
            model_name="city",
            name="name_without_article",
        ),
        migrations.RemoveField(
            model_name="city",
            name="uri_insee",
        ),
    ]
