# Generated by Django 4.1.7 on 2023-05-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0027_rename_created_at_city_established_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='established_at',
        ),
    ]
