# Generated by Django 4.1.7 on 2023-05-23 12:46
import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0029_alter_city_shape"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="shape",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=2154
            ),
        ),
    ]
