# Generated by Django 4.1.7 on 2023-05-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0030_alter_city_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='batid.city'),
        ),
    ]
