# Generated by Django 4.1.7 on 2023-05-23 13:40
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0030_alter_city_shape"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="batid.city"
            ),
        ),
    ]
