# Generated by Django 4.1.7 on 2023-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0031_ads_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='rnb_id',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
