# Generated by Django 4.1.7 on 2023-05-31 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0032_alter_building_rnb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('constructionProject', 'En projet'), ('canceledConstructionProject', 'Projet annulé'), ('ongoingConstruction', 'Construction en cours'), ('constructed', 'Construit'), ('ongoingChange', 'En cours de modification'), ('notUsable', 'Non utilisable'), ('demolished', 'Démoli')], db_index=True, max_length=30)),
                ('_happened_at', models.DateField()),
                ('happened_at_year', models.IntegerField(null=True)),
                ('happened_at_month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('happened_at_day', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='batid.building')),
            ],
        ),
    ]
