# Generated by Django 4.1.7 on 2023-05-31 09:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0033_buildingstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildingstatus",
            name="_happened_at",
        ),
        migrations.RemoveField(
            model_name="buildingstatus",
            name="happened_at_day",
        ),
        migrations.RemoveField(
            model_name="buildingstatus",
            name="happened_at_month",
        ),
        migrations.RemoveField(
            model_name="buildingstatus",
            name="happened_at_year",
        ),
        migrations.AddField(
            model_name="buildingstatus",
            name="happened_at",
            field=models.DateField(null=True),
        ),
    ]
