# Generated by Django 4.1.7 on 2023-06-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0034_remove_buildingstatus__happened_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingstatus',
            options={'ordering': [models.OrderBy(models.F('happened_at'), nulls_first=True)]},
        ),
        migrations.RenameField(
            model_name='buildingstatus',
            old_name='status',
            new_name='type',
        ),
    ]
