# Generated by Django 4.1.7 on 2023-06-02 07:49
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0035_alter_buildingstatus_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(db_index=True, max_length=20)),
                ("origin", models.CharField(db_index=True, max_length=20)),
                ("handled_at", models.DateTimeField(null=True)),
                ("handle_result", models.JSONField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("creator_copy_id", models.IntegerField(null=True)),
                ("creator_copy_fname", models.CharField(max_length=100, null=True)),
                ("creator_copy_lname", models.CharField(max_length=100, null=True)),
                ("creator_org_copy_id", models.IntegerField(null=True)),
                ("creator_org_copy_name", models.CharField(max_length=100, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="batid.building",
                    ),
                ),
            ],
        ),
    ]
