# Generated by Django 4.1.7 on 2023-06-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0036_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='origin',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
