# Generated by Django 4.1.7 on 2023-06-07 12:21
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0037_alter_signal_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ADSEnd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_number",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("end_date", models.DateField(null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
