# Generated by Django 4.1.7 on 2023-06-07 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0038_adsend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADSAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('achieved_at', models.DateField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ADSEnd',
        ),
        migrations.RenameField(
            model_name='ads',
            old_name='decision_date',
            new_name='decided_at',
        ),
        migrations.AddField(
            model_name='ads',
            name='achieved_at',
            field=models.DateField(null=True),
        ),
    ]
