# Generated by Django 4.1.7 on 2023-06-13 08:49
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0041_remove_ads_insee_code_address_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
