# Generated by Django 4.1.7 on 2023-06-20 08:35
import django.contrib.gis.db.models.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0043_ads_creator_buildingads_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=3, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=2154
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
