# Generated by Django 4.1.7 on 2023-06-20 09:09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0044_departement"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Departement",
            new_name="Department",
        ),
    ]
