# Generated by Django 4.1.7 on 2023-07-04 13:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0045_rename_departement_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="children",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="address_keys",
        ),
        migrations.AddField(
            model_name="candidate",
            name="addresses",
            field=models.JSONField(null=True),
        ),
        migrations.RemoveField(
            model_name="building",
            name="addresses",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.AddField(
            model_name="building",
            name="addresses",
            field=models.JSONField(null=True),
        ),
    ]
