# Generated by Django 4.1.7 on 2023-07-07 08:01
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0047_candidate_inspect_stamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("source", models.CharField(max_length=10)),
                ("street_number", models.CharField(max_length=10, null=True)),
                ("street_rep", models.CharField(max_length=5, null=True)),
                ("street_name", models.CharField(max_length=100, null=True)),
                ("street_type", models.CharField(max_length=100, null=True)),
                ("city_name", models.CharField(max_length=100, null=True)),
                ("city_zipcode", models.CharField(max_length=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="addresses",
        ),
        migrations.AddField(
            model_name="candidate",
            name="address_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=40), null=True, size=None
            ),
        ),
        migrations.RemoveField(
            model_name="building",
            name="addresses",
        ),
        migrations.AddField(
            model_name="building",
            name="addresses",
            field=models.ManyToManyField(
                blank=True, related_name="buildings", to="batid.address"
            ),
        ),
    ]
