# Generated by Django 4.1.7 on 2023-07-07 08:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0049_address_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city_insee_code",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
