# Generated by Django 4.1.7 on 2023-07-07 08:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0050_address_city_insee_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.CharField(
                db_index=True, max_length=40, primary_key=True, serialize=False
            ),
        ),
    ]
