# Generated by Django 4.1.7 on 2023-08-01 14:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0051_alter_address_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="ext_bdnb_id",
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="ext_bdtopo_id",
            field=models.CharField(db_index=True, max_length=40, null=True),
        ),
    ]
