# Generated by Django 4.1.7 on 2023-09-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0052_alter_building_ext_bdnb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_rep',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
