# Generated by Django 4.1.7 on 2023-09-22 15:47
import django.contrib.gis.db.models.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0052_alter_building_ext_bdnb_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True, max_length=40, primary_key=True, serialize=False
                    ),
                ),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.PolygonField(
                        null=True, srid=2154
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
