# Generated by Django 4.1.7 on 2023-09-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0053_alter_address_street_rep'),
        ('batid', '0053_plot'),
    ]

    operations = [
    ]
