# Generated by Django 4.1.7 on 2023-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0055_alter_plot_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingstatus',
            name='type',
            field=models.IntegerField(choices=[(0, 'constructionProject'), (1, 'canceledConstructionProject'), (2, 'ongoingConstruction'), (3, 'constructed'), (4, 'ongoingChange'), (5, 'notUsable'), (6, 'demolished')], default=3),
        ),
    ]
