# Generated by Django 4.1.7 on 2023-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0055_alter_plot_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='ext_bdnb_id',
        ),
        migrations.RemoveField(
            model_name='building',
            name='ext_bdtopo_id',
        ),
        migrations.AddField(
            model_name='building',
            name='ext_ids',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
