# Generated by Django 4.1.7 on 2023-10-30 13:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0055_alter_plot_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='shape_wgs84',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
