# Generated by Django 4.1.7 on 2023-11-02 13:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0056_building_shape_wgs84'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='shape_wgs84',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
