# Generated by Django 4.1.7 on 2023-11-06 08:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0057_candidate_is_shape_fictive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='shape_wgs84',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
