# Generated by Django 4.1.7 on 2023-11-15 17:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0058_alter_building_shape_wgs84"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingImport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("import_source", models.CharField(max_length=20)),
                ("bulk_launch_uuid", models.UUIDField(null=True)),
                ("departement", models.CharField(max_length=3, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_created_count", models.IntegerField(null=True)),
                ("building_created_count", models.IntegerField(null=True)),
                ("building_updated_count", models.IntegerField(null=True)),
                ("building_refused_count", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="last_updated_by",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="created_by",
            field=models.JSONField(null=True),
        ),
    ]
