# Generated by Django 4.1.7 on 2023-11-08 10:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0058_alter_building_shape_wgs84'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='shape',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=2154),
        ),
    ]
