# Generated by Django 4.1.7 on 2023-11-09 14:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0058_alter_building_shape_wgs84'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
