# Generated by Django 4.1.7 on 2023-11-09 14:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0059_alter_city_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
