# Generated by Django 4.1.7 on 2023-11-09 14:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0060_alter_department_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
