# Generated by Django 4.1.7 on 2023-11-28 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0061_rename_shape_wgs84_building_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='shape',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
