# Generated by Django 4.1.7 on 2023-11-09 16:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0061_alter_building_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
