# Generated by Django 4.1.7 on 2023-11-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0062_alter_candidate_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_shape_fictive',
        ),
    ]
