# Generated by Django 4.1.7 on 2023-11-23 08:27
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations
from django.db import models

import batid.models


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0062_temporal_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingWithHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rnb_id", models.CharField(db_index=True, max_length=12, unique=True)),
                ("source", models.CharField(db_index=True, max_length=10)),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.GeometryField(
                        null=True, srid=4326
                    ),
                ),
                ("ext_ids", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sys_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=batid.models.from_now_to_infinity
                    ),
                ),
                ("parent_buildings", models.JSONField(null=True)),
            ],
            options={
                "db_table": "batid_building_with_history",
                "managed": False,
            },
        ),
    ]
