# Generated by Django 4.1.7 on 2023-11-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0060_alter_address_point_alter_building_point_and_more'),
        ('batid', '0062_alter_candidate_shape'),
    ]

    operations = [
    ]
