# Generated by Django 4.1.7 on 2023-11-15 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0063_merge_20231115_1121"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="shape",
        ),
    ]
