# Generated by Django 4.1.7 on 2023-11-28 18:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0063_buildingwithhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_shape_fictive',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='shape',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
