# Generated by Django 4.1.7 on 2023-12-04 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0065_remove_candidate_inspect_result_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="source",
        ),
        migrations.RemoveField(
            model_name="buildinghistoryonly",
            name="source",
        ),
    ]
