# Generated by Django 4.1.7 on 2023-12-05 13:12
from django.db import migrations

from batid.migrations.utils.create_view import (
    sql_migration_building_with_history_create_view,
)
from batid.migrations.utils.create_view import (
    sql_migration_building_with_history_drop_view,
)


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0065_remove_candidate_inspect_result_and_more"),
    ]

    operations = [
        # Since Django 6.0, RemoveField no longer uses CASCADE on PostgreSQL,
        # so we must explicitly drop the view before removing columns it depends on.
        sql_migration_building_with_history_drop_view(),
        migrations.RemoveField(
            model_name="building",
            name="source",
        ),
        migrations.RemoveField(
            model_name="buildinghistoryonly",
            name="source",
        ),
        sql_migration_building_with_history_create_view(),
    ]
