# Generated by Django 4.1.7 on 2023-12-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0065_remove_candidate_inspect_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
