# Generated by Django 4.1.7 on 2023-12-05 13:12
from django.db import migrations

from batid.migrations.utils.create_view import sql_migration_building_with_history


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0065_remove_candidate_inspect_result_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="source",
        ),
        migrations.RemoveField(
            model_name="buildinghistoryonly",
            name="source",
        ),
        # the above migrations steps drop columns with "CASCADE" option
        # the building_with_history view is dropped by this cascade because it depends on the deleted column.
        # so we need to recreate it
        sql_migration_building_with_history(),
    ]
