# Generated by Django 4.1.7 on 2023-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0066_remove_building_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='random',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
