# Generated by Django 4.1.7 on 2023-12-05 16:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0066_remove_building_source_and_more"),
    ]

    operations = [
        # custom sql
        migrations.RunSQL(
            # destroy index
            """
                DROP INDEX batid_candidate_shape_e7d11d46_id;
            """,
            reverse_sql="""
                CREATE INDEX batid_candidate_shape_e7d11d46_id ON public.batid_candidate USING gist (shape);
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="candidate",
                    name="shape",
                    field=django.contrib.gis.db.models.fields.GeometryField(
                        null=True, spatial_index=False, srid=4326
                    ),
                )
            ],
        ),
    ]
