# Generated by Django 4.1.7 on 2023-12-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0066_remove_building_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='inspect_stamp',
        ),
    ]
