# Generated by Django 4.1.7 on 2023-12-05 16:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0067_alter_candidate_shape"),
    ]

    operations = [
        migrations.RunSQL(
            # destroy index
            """
                DROP INDEX batid_building_point_c8b72b20_id;
            """,
            reverse_sql="""
                CREATE INDEX batid_building_point_c8b72b20_id ON public.batid_building USING gist (point);
            """,
            state_operations=[
                migrations.AlterField(
                    model_name="building",
                    name="point",
                    field=django.contrib.gis.db.models.fields.PointField(
                        null=True, spatial_index=False, srid=4326
                    ),
                )
            ],
        ),
        migrations.RunSQL(
            # destroy index
            """
                DROP INDEX batid_building_history_point_fd5e74d2_id;
            """,
            reverse_sql="""
                    CREATE INDEX batid_building_history_point_fd5e74d2_id ON public.batid_building_history USING gist (point);
                """,
            state_operations=[
                migrations.AlterField(
                    model_name="buildinghistoryonly",
                    name="point",
                    field=django.contrib.gis.db.models.fields.PointField(
                        null=True, spatial_index=False, srid=4326
                    ),
                )
            ],
        ),
    ]
