# Generated by Django 4.1.7 on 2023-12-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0067_alter_candidate_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='inspect_stamp',
        ),
    ]
