# Generated by Django 4.1.7 on 2023-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0069_candidate_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_rep',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
