# Generated by Django 4.1.7 on 2023-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0069_candidate_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='inspect_stamp',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
