# Generated by Django 4.1.7 on 2023-12-19 09:44
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0070_alter_address_street_rep"),
    ]

    operations = [
        migrations.RunSQL(
            """
                create index batid_candidate_inspected_at_idx on public.batid_candidate (inspected_at, random);
            """,
            reverse_sql="""
                drop index batid_candidate_inspected_at_idx;
            """,
        ),
    ]
