# Generated by Django 4.1.7 on 2023-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0070_candidate_inspect_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='inspect_stamp',
        ),
        migrations.AddField(
            model_name='candidate',
            name='inspection_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
