# Generated by Django 4.1.7 on 2023-12-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0071_create_index_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rnb_id', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
