# Generated by Django 4.1.7 on 2023-12-19 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batid", "0072_contribution"),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE INDEX batid_plot_shape_geog ON public.batid_plot USING GIST (geography(shape));    
            """,
            reverse_sql="""
                drop index batid_plot_shape_geog;
            """,
        ),
        migrations.RunSQL(
            """
                CREATE INDEX batid_building_shape_geog ON public.batid_building USING GIST (geography(shape));    
            """,
            reverse_sql="""
                drop index batid_building_shape_geog;
            """,
        ),
    ]
