# Generated by Django 4.1.7 on 2024-03-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0073_create_index_geographic_index_bdg_plots'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='physical_status',
            field=models.CharField(choices=[('constructionProject', 'En projet'), ('canceledConstructionProject', 'Projet annulé'), ('ongoingConstruction', 'Construction en cours'), ('constructed', 'Construit'), ('ongoingChange', 'En cours de modification'), ('notUsable', 'Non utilisable'), ('demolished', 'Démoli')], db_index=True, default='constructed', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='buildinghistoryonly',
            name='physical_status',
            field=models.CharField(choices=[('constructionProject', 'En projet'), ('canceledConstructionProject', 'Projet annulé'), ('ongoingConstruction', 'Construction en cours'), ('constructed', 'Construit'), ('ongoingChange', 'En cours de modification'), ('notUsable', 'Non utilisable'), ('demolished', 'Démoli')], db_index=True, default='constructed', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='BuildingStatus',
        ),
    ]
