# Generated by Django 4.1.7 on 2024-03-13 14:44
from django.db import migrations

from batid.migrations.utils.create_view import sql_migration_building_with_history


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0074_building_physical_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="last_updated_by",
            new_name="event_origin",
        ),
        migrations.RenameField(
            model_name="buildinghistoryonly",
            old_name="last_updated_by",
            new_name="event_origin",
        ),
        sql_migration_building_with_history(),
    ]
