# Generated by Django 4.1.7 on 2024-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0075_rename_last_updated_by_building_event_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ext_id', models.CharField(db_index=True, max_length=255)),
                ('source_name', models.CharField(db_index=True, max_length=255)),
                ('matches', models.JSONField(null=True)),
                ('match_reason', models.CharField(db_index=True, max_length=255, null=True)),
                ('inputs', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['source_name', 'ext_id'],
                'unique_together': {('ext_id', 'source_name')},
            },
        ),
    ]
