# Generated by Django 4.1.7 on 2024-03-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0076_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='finished_steps',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
