# Generated by Django 4.1.7 on 2024-03-21 09:19
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batid", "0076_building_event_id_building_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="review_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="review_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
