# Generated by Django 4.1.7 on 2024-03-20 15:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0076_building_event_id_building_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="review_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
