# Generated by Django 4.1.7 on 2024-04-15 12:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0077_contribution_email_contribution_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buildingads',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='buildingads',
            name='rnb_id',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='buildingads',
            name='shape',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
        migrations.RemoveField(
            model_name='buildingads',
            name='building',
        ),
    ]
