# Generated by Django 4.1.7 on 2024-03-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0077_guess_finished_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
