# Generated by Django 4.1.13 on 2024-04-22 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batid', '0078_alter_buildingads_unique_together_buildingads_rnb_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='city',
        ),
        migrations.RemoveField(
            model_name='buildingads',
            name='creator',
        ),
        migrations.AlterField(
            model_name='ads',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
