# Generated by Django 4.1.7 on 2024-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0078_guess_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='finished_steps',
            field=models.JSONField(db_index=True, null=True),
        ),
    ]
