# Generated by Django 4.1.13 on 2024-04-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0079_remove_ads_city_remove_buildingads_creator_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buildingads',
            unique_together={('rnb_id', 'ads')},
        ),
    ]
