# Generated by Django 4.1.13 on 2024-05-16 11:36
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("batid", "0081_buildingaddressesreadonly_building_addresses_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="status",
            field=models.CharField(
                choices=[
                    ("constructionProject", "En projet"),
                    ("canceledConstructionProject", "Projet annulé"),
                    ("ongoingConstruction", "Construction en cours"),
                    ("constructed", "Construit"),
                    ("ongoingChange", "En cours de modification"),
                    ("notUsable", "Non utilisable"),
                    ("demolished", "Démoli"),
                ],
                default="constructed",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="buildinghistoryonly",
            name="status",
            field=models.CharField(
                choices=[
                    ("constructionProject", "En projet"),
                    ("canceledConstructionProject", "Projet annulé"),
                    ("ongoingConstruction", "Construction en cours"),
                    ("constructed", "Construit"),
                    ("ongoingChange", "En cours de modification"),
                    ("notUsable", "Non utilisable"),
                    ("demolished", "Démoli"),
                ],
                default="constructed",
                max_length=30,
            ),
        ),
        AddIndexConcurrently(
            model_name="building",
            index=models.Index(fields=["status"], name="bdg_status_idx"),
        ),
        AddIndexConcurrently(
            model_name="buildinghistoryonly",
            index=models.Index(fields=["status"], name="bdg_history_status_idx"),
        ),
    ]
