# Generated by Django 4.1.13 on 2024-05-27 12:35
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("batid", "0082_alter_building_status_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="building",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["sys_period"], name="bdg_sys_period_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="buildinghistoryonly",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["sys_period"], name="bdg_history_sys_period_idx"
            ),
        ),
    ]
