# Generated by Django 4.1.13 on 2024-05-27 12:28
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("batid", "0082_alter_building_status_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="building",
            index=models.Index(fields=["ext_ids"], name="bdg_ext_ids_idx"),
        ),
        # migrations.AlterField(
        #     model_name="building",
        #     name="ext_ids",
        #     field=models.JSONField(db_index=True, null=True),
        # ),
    ]
