# Generated by Django 4.1.13 on 2024-05-24 10:18
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("batid", "0082_alter_building_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creation", "creation"),
                    ("update", "update"),
                    ("deletion", "deletion"),
                    ("merge", "merge"),
                    ("split", "split"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="buildinghistoryonly",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creation", "creation"),
                    ("update", "update"),
                    ("deletion", "deletion"),
                    ("merge", "merge"),
                    ("split", "split"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        AddIndexConcurrently(
            model_name="building",
            index=models.Index(fields=["event_type"], name="bdg_event_type_idx"),
        ),
        AddIndexConcurrently(
            model_name="buildingaddressesreadonly",
            index=models.Index(
                fields=["address_id"], name="bdg_addr_readonly_address_id"
            ),
        ),
        AddIndexConcurrently(
            model_name="buildinghistoryonly",
            index=models.Index(
                fields=["event_type"], name="bdg_history_event_type_idx"
            ),
        ),
    ]
