# Generated by Django 4.1.13 on 2024-05-28 11:49
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("batid", "0083_building_bdg_sys_period_idx_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="building",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["ext_ids"], name="bdg_ext_ids_idx"
            ),
        ),
    ]
