# Generated by Django 4.1.13 on 2024-05-06 15:44
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0083_building_bdg_sys_period_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """CREATE SCHEMA IF NOT EXISTS opendata;

            DROP VIEW IF EXISTS opendata.rnb_compact;

            CREATE OR REPLACE VIEW opendata.rnb_compact AS
            SELECT bdg.rnb_id AS rnb_id, ST_AsText(bdg.point) AS point, ST_AsText(bdg.shape) AS shape, bdg.ext_ids AS ext_ids,
            json_agg(
                concat_ws(' ',
                    NULLIF(addr.street_number, ''),
                    NULLIF(addr.street_rep, ''),
                    NULLIF(addr.street_type, ''),
                    NULLIF(addr.street_name, ''),
                    NULLIF(addr.city_zipcode, ''),
                    NULLIF(addr.city_name, '')
                )
            ) AS addresses,
            dept.code AS code_dept
            FROM batid_building bdg
            LEFT JOIN batid_buildingaddressesreadonly bdg_addr ON bdg_addr.building_id = bdg.id
            LEFT JOIN batid_address addr ON addr.id = bdg_addr.address_id
            LEFT JOIN batid_department AS dept ON ST_Intersects(dept.shape, bdg.point)
            WHERE is_active
            GROUP BY bdg.rnb_id, bdg.point, bdg.shape, bdg.ext_ids, dept.code;
            """,
            reverse_sql="""DROP VIEW IF EXISTS opendata.rnb_compact;
            DROP SCHEMA IF EXISTS opendata;""",
        )
    ]
