# Generated by Django 4.1.13 on 2024-05-28 10:03
import django.db.models.functions.text
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("batid", "0083_building_bdg_sys_period_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="building",
            name="bdg_sys_period_idx",
        ),
        migrations.RemoveIndex(
            model_name="buildinghistoryonly",
            name="bdg_history_sys_period_idx",
        ),
        AddIndexConcurrently(
            model_name="building",
            index=models.Index(
                django.db.models.functions.text.Lower("sys_period"),
                name="bdg_sys_period_start_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="buildinghistoryonly",
            index=models.Index(
                django.db.models.functions.text.Lower("sys_period"),
                name="bdg_hist_sys_period_start_idx",
            ),
        ),
    ]
