# Generated by Django 4.1.13 on 2024-06-11 08:51
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0087_building_bdg_ext_ids_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={},
        ),
        migrations.RemoveField(
            model_name="building",
            name="addresses",
        ),
    ]
