# Generated by Django 4.1.13 on 2024-06-11 08:51
from django.db import migrations

from batid.migrations.utils.create_view import (
    sql_migration_building_with_history_create_view,
)
from batid.migrations.utils.create_view import (
    sql_migration_building_with_history_drop_view,
)


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0087_building_bdg_ext_ids_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={},
        ),
        # Since Django 6.0, RemoveField no longer uses CASCADE on PostgreSQL,
        # so we must explicitly drop the view before removing columns it depends on.
        sql_migration_building_with_history_drop_view(),
        migrations.RemoveField(
            model_name="building",
            name="addresses",
        ),
        sql_migration_building_with_history_create_view(),
    ]
