# Generated by Django 4.1.13 on 2024-07-01 14:39
import django.contrib.gis.db.models.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0088_alter_building_options_remove_building_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department_subdivided",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=200)),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.PolygonField(
                        null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            """
            INSERT INTO batid_department_subdivided (code, name, shape)
            SELECT code, name, ST_SubDivide(shape) as shape
            FROM batid_department;
            """,
            reverse_sql="DELETE FROM batid_department_subdivided;",
        ),
    ]
