# Generated by Django 5.0.7 on 2024-09-27 08:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0089_department_subdivided"),
    ]

    operations = [
        # the view is dropped, because it is less flexible than a query.
        # We don't want to run a migration each time we need to modify it.
        migrations.RunSQL(
            """DROP VIEW IF EXISTS opendata.data_gouv_publication;
                    DROP SCHEMA IF EXISTS opendata;""",
            reverse_sql="""CREATE SCHEMA IF NOT EXISTS opendata;

                    DROP VIEW IF EXISTS opendata.data_gouv_publication;

                    CREATE OR REPLACE VIEW opendata.data_gouv_publication AS
                    SELECT bdg.rnb_id AS rnb_id, ST_AsEWKT(bdg.point) AS point, ST_AsEWKT(bdg.shape) AS shape, status, bdg.ext_ids AS ext_ids,
                    json_agg(
                        concat_ws(' ',
                            NULLIF(addr.street_number, ''),
                            NULLIF(addr.street_rep, ''),
                            NULLIF(addr.street_type, ''),
                            NULLIF(addr.street_name, ''),
                            NULLIF(addr.city_zipcode, ''),
                            NULLIF(addr.city_name, '')
                        )
                    ) AS addresses,
                    dept.code AS code_dept
                    FROM batid_building bdg
                    LEFT JOIN batid_buildingaddressesreadonly bdg_addr ON bdg_addr.building_id = bdg.id
                    LEFT JOIN batid_address addr ON addr.id = bdg_addr.address_id
                    LEFT JOIN batid_department AS dept ON ST_Intersects(dept.shape, bdg.point)
                    WHERE is_active
                    GROUP BY bdg.rnb_id, bdg.point, bdg.shape, bdg.status, bdg.ext_ids, dept.code;
                    """,
        )
    ]
