# Generated by Django 5.0.7 on 2024-09-24 13:11
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0089_department_subdivided"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="building",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["parent_buildings"], name="bdg_parent_buildings_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="buildinghistoryonly",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["parent_buildings"], name="bdg_hist_parent_buildings_idx"
            ),
        ),
    ]
