# Generated by Django 5.0.7 on 2024-10-24 15:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0092_building_bdg_parent_buildings_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
