# Generated by Django 5.0.7 on 2024-10-25 13:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0093_address_street"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="street_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="street_type",
        ),
    ]
