# Generated by Django 5.0.7 on 2024-11-18 14:13
from django.db import migrations
from django.db import models

from batid.migrations.utils.create_view import sql_migration_building_with_history
from batid.migrations.utils.create_view import (
    sql_migration_building_with_history_drop_view,
)


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0094_remove_address_street_name_and_more"),
    ]

    operations = [
        # I need to first drop the view before updating the column
        sql_migration_building_with_history_drop_view(),
        migrations.AlterField(
            model_name="building",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creation", "creation"),
                    ("update", "update"),
                    ("deactivation", "deactivation"),
                    ("merge", "merge"),
                    ("split", "split"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="buildinghistoryonly",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creation", "creation"),
                    ("update", "update"),
                    ("deactivation", "deactivation"),
                    ("merge", "merge"),
                    ("split", "split"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        # and recreate the view afterwards
        sql_migration_building_with_history(),
    ]
