# Generated by Django 5.0.7 on 2024-11-28 11:15
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0095_alter_building_event_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="building",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "event_type__in",
                        ["creation", "update", "deactivation", "merge", "split"],
                    )
                ),
                name="valid_event_type_check",
            ),
        ),
    ]
