# Generated by Django 5.0.7 on 2024-11-28 14:31
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0095_alter_building_event_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creation", "creation"),
                    ("update", "update"),
                    ("deactivation", "deactivation"),
                    ("reactivation", "reactivation"),
                    ("merge", "merge"),
                    ("split", "split"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="buildinghistoryonly",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creation", "creation"),
                    ("update", "update"),
                    ("deactivation", "deactivation"),
                    ("reactivation", "reactivation"),
                    ("merge", "merge"),
                    ("split", "split"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "event_type__in",
                        [
                            "creation",
                            "update",
                            "deactivation",
                            "reactivation",
                            "merge",
                            "split",
                        ],
                    )
                ),
                name="valid_event_type_check",
            ),
        ),
    ]
