# Generated by Django 5.0.7 on 2024-12-06 15:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0096_alter_building_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot",
            name="source_version",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
