# Generated by Django 5.0.7 on 2025-01-09 11:57
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0097_plot_source_version"),
    ]

    operations = [
        migrations.RunSQL(
            """
                CREATE INDEX batid_building_is_active_status ON batid_building(is_active, status);
            """,
            reverse_sql="""
                DROP INDEX batid_building_is_active_status;
            """,
        ),
    ]
