# Generated by Django 5.0.10 on 2025-01-09 13:50
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0097_plot_source_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["is_active", "status"], name="batid_building_active_status"
            ),
        ),
    ]
