# Generated by Django 5.0.7 on 2024-12-09 15:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0098_building_batid_building_active_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="report",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="status_updated_by_event_id",
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
