# Generated by Django 5.0.10 on 2025-02-05 14:36

import batid.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0099_contribution_signalement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffusionDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.FloatField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('documentation_url', models.URLField(null=True)),
                ('publisher', models.CharField(max_length=255, null=True)),
                ('licence', models.CharField(max_length=255, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_summary', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=list, validators=[batid.validators.JSONSchemaValidator({'items': {'additionalProperties': False, 'properties': {'description': {'type': 'string'}, 'name': {'type': 'string'}}, 'required': ['name', 'description'], 'type': 'object'}, 'type': 'array'})])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
