# Generated by Django 5.1.6 on 2025-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batid', '0100_diffusiondatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('source_version', models.CharField(max_length=20, null=True)),
                ('source_territory', models.CharField(max_length=20, null=True)),
                ('bulk_launch_uuid', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stats', models.JSONField(null=True)),
            ],
        ),
    ]
