# Generated by Django 5.1.6 on 2025-03-27 13:41
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0102_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AsyncSignal",
        ),
    ]
