# Generated by Django 5.2.1 on 2025-07-01 12:12
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0102_kpi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SummerChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("rnb_id", models.CharField(db_index=True, max_length=12)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("update_address", "update_address"),
                            ("update_shape", "update_shape"),
                            ("update_status", "update_status"),
                            ("creation", "creation"),
                            ("merge", "merge"),
                            ("split", "split"),
                            ("deactivation", "deactivation"),
                        ],
                        db_index=True,
                        max_length=14,
                    ),
                ),
                ("event_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="batid.city",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="batid.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
