# Generated by Django 5.2.1 on 2025-06-23 14:26

from django.db import migrations


forward_sql = """
ALTER TABLE batid_building 
SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 100000);

ALTER TABLE batid_building_history 
SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 100000);
"""


reverse_sql = """
ALTER TABLE batid_building 
RESET (autovacuum_vacuum_scale_factor, autovacuum_vacuum_threshold);

ALTER TABLE batid_building_history 
RESET (autovacuum_vacuum_scale_factor, autovacuum_vacuum_threshold);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0102_kpi"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forward_sql,
            reverse_sql=reverse_sql,
            state_operations=[
                migrations.AlterModelTable(
                    name="Building",
                    table="batid_building",
                ),
                migrations.AlterModelTable(
                    name="BuildingHistoryOnly",
                    table="batid_building_history",
                ),
            ],
        ),
    ]
