# Generated by Django 5.2.1 on 2025-06-10 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0102_kpi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="buildinghistoryonly",
            constraint=models.UniqueConstraint(
                fields=("rnb_id", "event_id"), name="unique_rnb_id_event_type"
            ),
        ),
    ]
