# Generated by Django 5.1.6 on 2025-04-10 05:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0102_kpi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kpi",
            options={"ordering": ["value_date"]},
        ),
        migrations.RenameField(
            model_name="kpi",
            old_name="computed_at",
            new_name="value_date",
        ),
    ]
