# Generated by Django 5.1.6 on 2025-04-10 05:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0103_alter_kpi_options_rename_computed_at_kpi_value_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpi",
            name="value_date",
            field=models.DateField(null=True),
        ),
    ]
