# Generated by Django 5.1.6 on 2025-04-10 06:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0104_alter_kpi_value_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="kpi",
            unique_together={("name", "value_date")},
        ),
    ]
