# Generated by Django 5.2.1 on 2025-06-23 14:50
from django.db import migrations


forward_sql = """
DROP INDEX IF EXISTS batid_building_event_id_82b1dcb8;
"""
reverse_sql = """
CREATE INDEX batid_building_event_id_82b1dcb8 ON public.batid_building USING btree (event_id);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0105_auto_vacuum_buildings"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forward_sql,
            reverse_sql=reverse_sql,
            state_operations=[
                migrations.AlterModelTable(
                    name="Building",
                    table="batid_building",
                ),
            ],
        ),
    ]
