# Generated by Django 5.2.1 on 2025-07-16 13:44

from django.db import migrations
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import models


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("batid", "0106_remove_event_id_idx"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="building",
            index=models.Index(fields=["event_id"], name="bdg_event_id_idx"),
        ),
        AddIndexConcurrently(
            model_name="buildinghistoryonly",
            index=models.Index(fields=["event_id"], name="bdg_history_event_id_idx"),
        ),
    ]
