# Generated by Django 5.2.1 on 2025-07-16 13:44
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("batid", "0106_remove_event_id_idx"),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = '0';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        AddIndexConcurrently(
            model_name="building",
            index=models.Index(fields=["event_id"], name="bdg_event_id_idx"),
        ),
    ]
