# Generated by Django 5.2.1 on 2025-06-10 09:14
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0107_add_event_id_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = '0';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="buildinghistoryonly",
            constraint=models.UniqueConstraint(
                fields=("rnb_id", "event_id"), name="unique_rnb_id_event_type"
            ),
        ),
    ]
