# Generated by Django 5.2.2 on 2025-08-07 13:26
import django.contrib.postgres.indexes
from django.contrib.postgres import operations
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("batid", "0107_add_event_id_idx"),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = '3600000';",  # 60 min
            reverse_sql=migrations.RunSQL.noop,
        ),
        operations.CreateExtension("btree_gist"),
        operations.AddIndexConcurrently(
            model_name="building",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["point", "id"], name="bdg_point_id_btree_gist_idx"
            ),
        ),
        operations.AddIndexConcurrently(
            model_name="building",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["id", "point"], name="bdg_id_point_btree_gist_idx"
            ),
        ),
    ]
