# Generated by Django 5.2.2 on 2025-09-30 10:14
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.db import models

import batid.models.building


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0108_building_unique_rnb_id_event_type_building"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = '3600000';",  # 60 min
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="building",
            index=django.contrib.postgres.indexes.GistIndex(
                models.F("point"),
                batid.models.building.PGPoint(models.F("id"), 0),
                name="bdg_point_id_gist_idx",
            ),
        ),
    ]
