# Generated by Django 5.2.2 on 2025-09-24 08:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0108_building_add_random_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="random_id",
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        )
    ]
