# Generated by Django 5.2.6 on 2025-10-14 15:14

from django.db import migrations


forward_sql = """
ALTER TABLE batid_building
SET (autovacuum_analyze_scale_factor = 0, autovacuum_analyze_threshold = 1000);
"""


reverse_sql = """
ALTER TABLE batid_building
RESET (autovacuum_analyze_scale_factor, autovacuum_analyze_threshold);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0108_building_unique_rnb_id_event_type_building"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forward_sql,
            reverse_sql=reverse_sql,
            state_operations=[
                migrations.AlterModelTable(
                    name="Building",
                    table="batid_building",
                ),
            ],
        ),
    ]
