# Generated by Django 5.2.2 on 2025-09-24 08:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0108_building_unique_rnb_id_event_type_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="random_id",
            field=models.BigIntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pgcrypto;",
            reverse_sql="DROP EXTENSION IF EXISTS pgcrypto;",
        ),
    ]
