# Generated by Django 5.2.2 on 2025-09-30 10:14
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.db import models

import batid.models.building


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0108_building_unique_rnb_id_event_type_building"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS "bdg_point_id_gist_idx" ON "batid_building" USING gist ("point", (point("id", 0)));
            """,
            reverse_sql="DROP INDEX bdg_point_id_gist_idx;",
            # writing the sql by hand allows us to add "if not exists"
            # this statement will be executed manually on the DB to avoid downtime
            state_operations=[
                migrations.AddIndex(
                    model_name="building",
                    index=django.contrib.postgres.indexes.GistIndex(
                        models.F("point"),
                        batid.models.building.PGPoint(models.F("id"), 0),
                        name="bdg_point_id_gist_idx",
                    ),
                )
            ],
        ),
    ]
