# Generated by Django 5.2.6 on 2025-10-15 09:42
from django.db import migrations


forward_sql = """
ALTER TABLE batid_building
ALTER COLUMN ext_ids SET STATISTICS 10000;

ALTER TABLE batid_candidate
SET (
    autovacuum_vacuum_scale_factor = 0.05,
    autovacuum_analyze_scale_factor = 0.05
);
"""


reverse_sql = """
ALTER TABLE batid_building
ALTER COLUMN ext_ids SET STATISTICS DEFAULT;

ALTER TABLE batid_candidate
RESET (
    autovacuum_vacuum_scale_factor,
    autovacuum_analyze_scale_factor
);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0110_create_multi_column_gist_index"),
    ]

    operations = [
        migrations.RunSQL(
            sql=forward_sql,
            reverse_sql=reverse_sql,
            state_operations=[
                migrations.AlterModelTable(
                    name="Building",
                    table="batid_building",
                ),
                migrations.AlterModelTable(
                    name="Candidate",
                    table="batid_candidate",
                ),
            ],
        ),
    ]
