# Generated by Django 5.2.6 on 2025-10-30 09:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0110_create_multi_column_gist_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("fixed", "Corrigé"),
                            ("rejected", "Refusé"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "created_by_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="batid.building",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="closed_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closed_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["status"], name="report_status_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["created_at"], name="report_created_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("created_by_user__isnull", False),
                        ("created_by_email__isnull", True),
                    ),
                    models.Q(
                        ("created_by_user__isnull", True),
                        ("created_by_email__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="report_creator_exclusive",
            ),
        ),
    ]
