# Generated by Django 5.2.6 on 2025-10-30 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0111_add_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("text", models.TextField(default=None)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddField(
            model_name="reportmessage",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_report_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reportmessage",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="batid.report",
            ),
        ),
        migrations.AddIndex(
            model_name="reportmessage",
            index=models.Index(
                fields=["report", "timestamp"], name="report_message_report_ts_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("created_by_user__isnull", False),
                        ("created_by_email__isnull", True),
                    ),
                    models.Q(
                        ("created_by_user__isnull", True),
                        ("created_by_email__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="report_message_creator_exclusive",
            ),
        ),
    ]
