# Generated by Django 5.2.2 on 2025-11-18 14:12
from django.conf import settings
from django.db import migrations
from django.db import models

from batid.migrations.utils.create_view import (
    sql_migration_building_with_history_create_view,
)
from batid.migrations.utils.create_view import (
    sql_migration_building_with_history_drop_view,
)


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0112_create_report_reportmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        sql_migration_building_with_history_drop_view(),
        migrations.RemoveConstraint(
            model_name="building",
            name="valid_event_type_check",
        ),
        migrations.AddField(
            model_name="building",
            name="revert_event_id",
            field=models.UUIDField(null=True, db_index=True),
        ),
        migrations.AddField(
            model_name="buildinghistoryonly",
            name="revert_event_id",
            field=models.UUIDField(null=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creation", "creation"),
                    ("revert_creation", "revert_creation"),
                    ("deactivation", "deactivation"),
                    ("reactivation", "reactivation"),
                    ("update", "update"),
                    ("revert_update", "revert_update"),
                    ("merge", "merge"),
                    ("revert_merge", "revert_merge"),
                    ("split", "split"),
                    ("revert_split", "revert_split"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="buildinghistoryonly",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("creation", "creation"),
                    ("revert_creation", "revert_creation"),
                    ("deactivation", "deactivation"),
                    ("reactivation", "reactivation"),
                    ("update", "update"),
                    ("revert_update", "revert_update"),
                    ("merge", "merge"),
                    ("revert_merge", "revert_merge"),
                    ("split", "split"),
                    ("revert_split", "revert_split"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="building",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_type__in",
                        [
                            "creation",
                            "revert_creation",
                            "deactivation",
                            "reactivation",
                            "update",
                            "revert_update",
                            "merge",
                            "revert_merge",
                            "split",
                            "revert_split",
                        ],
                    )
                ),
                name="valid_event_type_check",
            ),
        ),
        migrations.AlterModelTable(
            name="building",
            table=None,
        ),
        sql_migration_building_with_history_create_view(),
    ]
