# Generated by Django 5.2.6 on 2025-11-03 13:07
from datetime import datetime

from django.contrib.auth.models import User
from django.contrib.gis.geos import Point
from django.db import migrations

from batid.models import Building
from batid.models import Contribution
from batid.models import Report
from batid.models import ReportMessage

status_mapping: dict[str, str] = {
    "pending": "pending",
    "fixed": "fixed",
    "refused": "rejected",
}


def validate_contribution(contribution: Contribution) -> None:
    if not contribution.rnb_id:
        raise ValueError(f"Contribution {contribution.id} has no rnb_id")
    if contribution.status not in status_mapping:
        raise ValueError(
            f"Contribution {contribution.id} has unexpected status: {contribution.status}"
        )
    if contribution.status in ["fixed", "refused"] and not contribution.review_user:
        raise ValueError(
            f"Closed contribution {contribution.id} is {contribution.status} but has no review_user"
        )
    if (
        contribution.status in ["fixed", "refused"]
        and not contribution.status_changed_at
    ):
        raise ValueError(
            f"Closed contribution {contribution.id} is {contribution.status} but has no status_changed_at timestamp"
        )
    if not contribution.text:
        raise ValueError(f"Contribution {contribution.id} has no text content")


def is_rejected_empty_contribution(contribution: Contribution) -> bool:
    return (
        contribution.status == "refused"
        and not contribution.text
        and (contribution.email is None or contribution.email == "testing@example.com")
    )


def migrate_single_contribution(contribution: Contribution) -> None:
    if is_rejected_empty_contribution(contribution):
        return

    validate_contribution(contribution)

    building: Building = Building.objects.get(rnb_id=contribution.rnb_id)

    new_report_status: str = status_mapping[contribution.status]
    new_report_email: str | None = contribution.email
    new_report_created_at: datetime = contribution.created_at
    new_report_updated_at: datetime = (
        contribution.status_changed_at
        if contribution.status_changed_at
        else contribution.updated_at
    )
    new_report_point: Point = building.point

    new_report_closed_by_user: User | None = (
        contribution.review_user
        if contribution.status in ["fixed", "refused"]
        else None
    )

    report = Report(
        point=new_report_point,
        building_id=building.pk,
        status=new_report_status,
        created_by_email=new_report_email,
        closed_by_user_id=(
            new_report_closed_by_user.pk if new_report_closed_by_user else None
        ),
        created_at=new_report_created_at,
        updated_at=new_report_updated_at,
    )
    report.save()
    report.tags.set(["Jeu de l'été 2024"])
    messages = []

    messages.append(
        ReportMessage(
            report=report,
            created_by_email=new_report_email,
            text=contribution.text,
            created_at=new_report_created_at,
        )
    )

    if contribution.review_comment and contribution.review_user:
        messages.append(
            ReportMessage(
                report=report,
                created_by_user_id=(
                    new_report_closed_by_user.pk if new_report_closed_by_user else None
                ),
                text=contribution.review_comment,
                created_at=contribution.status_changed_at,
            )
        )

    ReportMessage.objects.bulk_create(messages)


def disable_created_at_auto_now_add(apps, schema_editor):
    field = Report._meta.get_field("created_at")
    field.auto_now_add = False
    field = Report._meta.get_field("updated_at")
    field.auto_now = False
    field = ReportMessage._meta.get_field("created_at")
    field.auto_now_add = False


def enable_created_at_auto_now_add(apps, schema_editor):
    field = Report._meta.get_field("created_at")
    field.auto_now_add = True
    field = Report._meta.get_field("updated_at")
    field.auto_now = True
    field = ReportMessage._meta.get_field("created_at")
    field.auto_now_add = True


def migrate_contributions_to_report(apps, schema_editor):
    disable_created_at_auto_now_add(apps, schema_editor)
    Contribution = apps.get_model("batid", "Contribution")

    # Get all contributions that are reports
    contributions_to_migrate = Contribution.objects.filter(report=True)

    print(f"Found {contributions_to_migrate.count()} contributions to migrate")

    migrated_count = 0

    for contribution in contributions_to_migrate:
        migrate_single_contribution(contribution)

        migrated_count += 1

    enable_created_at_auto_now_add(apps, schema_editor)

    print(f"Migration completed: {migrated_count} contributions migrated successfully")


def reverse_migrate_contributions_to_report(apps, schema_editor):
    Report = apps.get_model("batid", "Report")
    ReportMessage = apps.get_model("batid", "ReportMessage")

    ReportMessage.objects.all().delete()
    Report.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0113_add_reportmessage"),
    ]

    operations = [
        migrations.RunPython(
            migrate_contributions_to_report, reverse_migrate_contributions_to_report
        ),
    ]
