# Generated by Django 5.2.8 on 2025-12-09 09:27
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0116_remove_building_valid_event_type_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="creation_batch_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
