# Generated by Django 5.2.9 on 2025-12-15 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0117_report_creation_batch_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diffusiondatabase",
            options={"ordering": ["display_order"]},
        ),
        migrations.CreateModel(
            name="EventDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(max_length=255)),
                ("event_origin", models.JSONField()),
                (
                    "city",
                    models.ForeignKey(
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="batid.city",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="batid.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuildingEventDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(db_index=True)),
                ("rnb_id", models.CharField(db_index=True, max_length=12)),
                ("changes", models.JSONField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "rnb_id"), name="unique_event_id_rnb_id"
                    )
                ],
            },
        ),
    ]
