# Generated by Django 5.2.9 on 2026-01-13 15:32
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0118_feve_galette"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diffusiondatabase",
            options={"ordering": ["display_order"]},
        ),
    ]
