# Generated by Django 5.2.9 on 2025-12-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0118_add_eventdetail"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            
            -- Placeholder function to compute the diff between a building and its previous version
            CREATE OR REPLACE FUNCTION public.compute_building_diff_from_last_version(
                building batid_building
            )
            RETURNS JSONB AS $$
            BEGIN
                RETURN '{}'::jsonb;
            END;
            $$ LANGUAGE plpgsql;

            -- Create a function instead of just a trigger to be able to call it from outside (for instance for backfilling)
            CREATE OR REPLACE FUNCTION public.insert_or_update_event_detail(
                building batid_building
            )
            RETURNS VOID AS $$
            DECLARE
                v_city_id INTEGER;
                v_department_id INTEGER;
            BEGIN
                IF building.event_id IS NULL OR building.event_type IS NULL OR building.event_origin IS NULL OR building.point IS NULL THEN
                    RAISE EXCEPTION 'Missing required parameters';
                END IF;

                -- The building shape can overlap multiple cities and departments, but we keep a single one
                -- out of simplicity
                SELECT id INTO v_city_id
                FROM batid_city AS c
                WHERE ST_Intersects(c.shape, building.point)
                LIMIT 1;

                SELECT id INTO v_department_id
                FROM batid_department AS d
                WHERE ST_Intersects(d.shape, building.point)
                LIMIT 1;

                -- We don't specifically check out-of-bounds in the RNB, but I think we ordinarily want buildings to land in French territory
                IF v_city_id IS NULL OR v_department_id IS NULL THEN
                    RAISE EXCEPTION 'No city or department found for the building point';
                END IF;

                INSERT INTO batid_eventdetail (
                    event_id,
                    event_type,
                    event_origin,
                    city_id,
                    department_id,
                    user_id
                )
                VALUES (
                    building.event_id,
                    building.event_type,
                    building.event_origin,
                    v_city_id,
                    v_department_id,
                    building.event_user_id
                )
                ON CONFLICT (event_id) DO UPDATE SET
                    event_type = EXCLUDED.event_type,
                    event_origin = EXCLUDED.event_origin,
                    city_id = EXCLUDED.city_id,
                    department_id = EXCLUDED.department_id,
                    user_id = EXCLUDED.user_id;

                INSERT INTO batid_buildingeventdetail (
                    event_id,
                    rnb_id,
                    changes
                )
                VALUES (
                    building.event_id,
                    building.rnb_id,
                    compute_building_diff_from_last_version(building)
                );
            END;
            $$ LANGUAGE plpgsql;

            -- Trigger that calls the function
            CREATE OR REPLACE FUNCTION public.upsert_event_detail_trigger()
            RETURNS TRIGGER AS $$
            BEGIN
                PERFORM insert_or_update_event_detail(NEW);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            -- Create unique index on event_id for the ON CONFLICT clause
            CREATE UNIQUE INDEX IF NOT EXISTS batid_eventdetail_event_id_unique
            ON batid_eventdetail (event_id);

            -- Create trigger for INSERT and UPDATE on batid_building
            -- Name it like this to make sure it executes after the versioning trigger
            CREATE TRIGGER building_versioning_trigger_1_insert_or_update_event_detail_trigger
            AFTER INSERT OR UPDATE ON batid_building
            FOR EACH ROW EXECUTE FUNCTION upsert_event_detail_trigger();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS building_versioning_trigger_1_insert_or_update_event_detail_trigger ON batid_building;
            DROP INDEX IF EXISTS batid_eventdetail_event_id_unique;
            DROP FUNCTION IF EXISTS public.upsert_event_detail_trigger();
            DROP FUNCTION IF EXISTS public.insert_or_update_event_detail(batid_building);
            DROP FUNCTION IF EXISTS public.compute_building_diff_from_last_version(batid_building);
            """,
        ),
    ]
