# Generated by Django 5.2.9 on 2026-01-19 13:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0119_alter_diffusiondatabase_options"),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = '0';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="address",
            name="ban_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
