# Generated by Django 5.2.9 on 2025-12-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0119_add_eventdetail_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingEventDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(db_index=True)),
                ("rnb_id", models.CharField(db_index=True, max_length=12)),
                ("changes", models.JSONField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "rnb_id"), name="unique_event_id_rnb_id"
                    )
                ],
            },
        ),
    ]
