# Generated by Django 5.2.10 on 2026-02-05 14:24
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0120_address_ban_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = '0';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="address",
            name="still_exists",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="buildinghistoryonly",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["addresses_id"], name="bdg_history_addresses_id_idx"
            ),
        ),
    ]
