# Generated by Django 5.2.10 on 2026-02-10 11:27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0121_address_still_exists_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = '0';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="address",
            name="ban_update_flag",
            field=models.CharField(
                db_index=True, default=None, max_length=20, null=True
            ),
        ),
    ]
