# Generated by Django 5.2.10 on 2026-02-10 15:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0122_address_ban_update_flag"),
    ]

    operations = [
        migrations.RunSQL(
            "SET statement_timeout = '0';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="address",
            name="ban_update_details",
            field=models.JSONField(default=None, null=True),
        ),
    ]
