# Generated by Django 6.0.1 on 2026-03-02 10:19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0123_address_ban_update_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="status",
            field=models.CharField(
                choices=[
                    ("constructed", "Construit"),
                    ("notUsable", "Non utilisable"),
                    ("demolished", "Démoli"),
                ],
                default="constructed",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="buildinghistoryonly",
            name="status",
            field=models.CharField(
                choices=[
                    ("constructed", "Construit"),
                    ("notUsable", "Non utilisable"),
                    ("demolished", "Démoli"),
                ],
                default="constructed",
                max_length=30,
            ),
        ),
    ]
