# Generated by Django 6.0.3 on 2026-04-08 09:34
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0125_prevent_address_deletion_if_linked_to_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffusiondatabase",
            name="is_displayed",
            field=models.BooleanField(default=True, verbose_name="visible sur le site"),
        ),
        migrations.AlterField(
            model_name="diffusiondatabase",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="visible sur la home (featured)"
            ),
        ),
    ]
