# Generated by Django 6.0.4 on 2026-04-17 13:46
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0126_diffusiondatabase_is_displayed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="batid.organization",
            ),
        ),
    ]
