# Generated by Django 6.0.4 on 2026-04-17 08:08
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0127_proconnectidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="proconnectidentity",
            name="siret",
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
