# Generated by Django 6.0.4 on 2026-04-17 15:07
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0128_populate_userprofile_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="users",
        ),
    ]
