# Generated by Django 6.0.4 on 2026-04-17 11:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0128_proconnectidentity_siret"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email_domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="siren",
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
