# Generated by Django 6.0.4 on 2026-05-12 08:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0132_create_rnb_team_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="marked_as_correct_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], null=True
            ),
        ),
        migrations.AddField(
            model_name="buildinghistoryonly",
            name="marked_as_correct_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], null=True
            ),
        ),
    ]
