# Generated by Django 6.0.4 on 2026-05-12 08:18

import django.contrib.postgres.fields
import django.db.models.deletion
from batid.migrations.utils.create_view import sql_migration_building_with_history
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0132_create_rnb_team_organization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="marked_as_correct_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], null=True
            ),
        ),
        migrations.AddField(
            model_name="buildinghistoryonly",
            name="marked_as_correct_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], null=True
            ),
        ),
        migrations.CreateModel(
            name="BuildingMarkedAsCorrectByReadOnly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="batid.building"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("building", "user")},
            },
        ),
        migrations.AddField(
            model_name="building",
            name="marked_as_correct_read_only",
            field=models.ManyToManyField(
                blank=True,
                related_name="buildings_marked_as_correct_read_only",
                through="batid.BuildingMarkedAsCorrectByReadOnly",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        sql_migration_building_with_history(),
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION public.keep_building_marked_as_correct_by_updated()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $function$
            DECLARE
                user_id INT;
            BEGIN
                IF TG_OP = 'INSERT' THEN
                    -- Loop through each user id in the marked_as_correct_by array

                    iF (NEW.marked_as_correct_by IS NOT NULL) THEN
                        FOREACH user_id IN ARRAY NEW.marked_as_correct_by
                        LOOP
                            -- Insert a row into table2 for each user id
                            INSERT INTO batid_buildingmarkedascorrectbyreadonly (building_id, user_id) VALUES (NEW.id, user_id);
                        END LOOP;
                    END IF;
                END IF;

                IF TG_OP = 'UPDATE' THEN
                    -- Check if the marked_as_correct_by column's content has changed
                    IF NEW.marked_as_correct_by IS DISTINCT FROM  OLD.marked_as_correct_by THEN
                        -- Delete existing rows related to the updated row in join table
                        DELETE FROM batid_buildingmarkedascorrectbyreadonly WHERE building_id = NEW.id;

                        -- Loop through each user id in the marked_as_correct_by array
                        iF (NEW.marked_as_correct_by IS NOT NULL) THEN
                            FOREACH user_id IN ARRAY NEW.marked_as_correct_by
                            LOOP
                                -- Insert a row into join table for each user id
                                INSERT INTO batid_buildingmarkedascorrectbyreadonly (building_id, user_id) VALUES (NEW.id, user_id);
                            END LOOP;
                        END IF;
                    END IF;
                END IF;

                RETURN NEW;
            END;
            $function$
            ;

            create trigger building_marked_as_correct_by_trigger AFTER insert or update on public.batid_building for each row execute function keep_building_marked_as_correct_by_updated();
""",
            reverse_sql="""
            DROP TRIGGER building_marked_as_correct_by_trigger ON batid_building;
            DROP FUNCTION keep_building_marked_as_correct_by_updated();
            """,
        ),
    ]
