# Generated by Django 6.0.4 on 2026-05-18 13:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0132_create_rnb_team_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="managed_cities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=6), blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="batid.organization",
            ),
        ),
    ]
