# Generated by Django 6.0.4 on 2026-05-12 15:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0133_building_marked_as_correct_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="marked_as_correct_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, null=True
            ),
        ),
        migrations.AlterField(
            model_name="buildinghistoryonly",
            name="marked_as_correct_by",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="batid.organization",
            ),
        ),
    ]
