# Generated by Django 6.0.4 on 2026-06-03 15:08

from django.db import migrations


def delete_orphaned_reports(apps, schema_editor):
    """
    Delete the now-redundant report=True contributions, EXCEPT those still
    referenced by a building version through event_origin->>'contribution_id'.
    Referenced rows are kept to avoid dangling ids in Building / history; once
    the report column is dropped they simply become ordinary edit contributions.

    batid_building_with_history is an unmanaged DB view, so we query it directly.
    """
    with schema_editor.connection.cursor() as cursor:
        # The DELETE scans the whole building history view and can run for a
        # long time on production, so we lift any statement timeout for it.
        cursor.execute("SET statement_timeout = 0;")
        cursor.execute("""
            DELETE FROM batid_contribution c
            WHERE c.report = true
              AND NOT EXISTS (
                SELECT 1 FROM batid_building_with_history h
                WHERE h.event_origin->>'source' = 'contribution'
                  AND (h.event_origin->>'contribution_id')::bigint = c.id
              )
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0138_rename_contribution_review_user_to_user"),
    ]

    operations = [
        migrations.RunPython(delete_orphaned_reports, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="contribution",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="report",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="review_comment",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="status",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="status_changed_at",
        ),
        migrations.RemoveField(
            model_name="contribution",
            name="status_updated_by_event_id",
        ),
    ]
