# Generated by Django 6.0.6 on 2026-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0140_organization_short_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summerchallenge",
            name="score",
        ),
        migrations.AlterField(
            model_name="summerchallenge",
            name="action",
            field=models.CharField(
                choices=[
                    ("set_address", "set_address"),
                    ("update_shape", "update_shape"),
                    ("update_status", "update_status"),
                    ("creation", "creation"),
                    ("merge", "merge"),
                    ("split", "split"),
                    ("deactivation", "deactivation"),
                    ("validation", "validation"),
                ],
                db_index=True,
                max_length=14,
            ),
        ),
    ]
