# Generated by Django 6.0.6 on 2026-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0141_remove_summerchallenge_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotificationOptOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
