# Generated by Django 6.0.6 on 2026-06-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0141_remove_summerchallenge_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditionAnnotation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("correct", "correct"),
                            ("uncertain", "uncertain"),
                            ("incorrect", "incorrect"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editions_annotated_by_reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editions_annotated_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "reviewer"),
                        name="unique_annotation_per_reviewer_per_edition",
                    )
                ],
            },
        ),
    ]
