# Generated by Django 6.0.6 on 2026-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0144_eventannotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="comment_from_reviewer",
            field=models.TextField(blank=True),
        ),
    ]
