# Generated by Django 6.0.7 on 2026-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batid", "0156_address_internal_id_primary_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="has_reliable_ban_ids",
            field=models.BooleanField(null=True),
        ),
    ]
