name: Deploy application on production & sandbox servers
on:
    push:
        branches:
            - main

permissions:
  contents: read

jobs:
    deployment:
        name: Deployment on production & sandbox servers
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: connect to the production server with ssh and run commands to deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: cd /srv/RNB-coeur && git pull && docker compose -f docker-compose.prod.yml build --no-cache && docker compose -f docker-compose.prod.yml up -d
            - name: connect to the sandbox server with ssh and run commands to deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SANDBOX_SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: cd /srv/RNB-coeur && git pull && docker compose -f docker-compose.sandbox.yml build --no-cache && docker compose -f docker-compose.sandbox.yml up -d
