name: Deploy application on production server
on:
    push:
        branches:
            - main
            - continuous_deployment
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: connect to server with ssh and run commands to deploy
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: whoami