name: Deploy application on staging server
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
    deployment:
        name: Deployment on staging server
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: connect to server with ssh and run commands to deploy
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: cd /srv/RNB-coeur && git fetch && git checkout ${{ github.ref_name }} && git reset --hard origin/${{ github.ref_name }} && docker compose -f docker-compose.staging.yml build --no-cache && docker compose -f docker-compose.staging.yml up -d
