name: Lint

on:
  push:
    branches: [sp3-ci]
  pull_request:
    branches: [main, develop]

jobs:
  flake8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Run flake8
        run: |
          pip install flake8
          flake8 --version
          flake8
