name: tests

on:
  pull_request:
    branches: [develop]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
    steps:
      - uses: actions/checkout@v3
        run: docker-compose -f docker-compose.test.yml up -d --build
      - name: Run docker test
        run:  docker-compose -f docker-compose.test.yml exec -T web python manage.py test
